services:
    _defaults:
            autowire: true
            autoconfigure: true
            public: false

    Ergonode\Core\Persistence\:
        resource: '../../Persistence/*'

    Ergonode\Core\Application\:
        resource: '../../Application/*'

    Ergonode\Core\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{Entity, ValueObject}'

    Ergonode\Core\Application\Controller\:
        resource: '../../Application/Controller'
        tags: ['controller.service_arguments']

    Ergonode\Core\Infrastructure\:
        resource: '../../Infrastructure/*'

    Ergonode\Core\Infrastructure\JMS\Serializer\Handler\:
        resource: '../../Infrastructure/JMS/Serializer/Handler/*'
        tags: ['jms_serializer.subscribing_handler']

    Ergonode\Core\Application\Provider\SimpleDirectoryProvider:
        arguments:
            $directory: '%kernel.project_dir%'

    Ergonode\Core\Application\EventListener\RequestBodyListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', priority: 1024 }

    Ergonode\Core\Application\EventListener\ExceptionListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception', priority: 1024 }

    Ergonode\Core\Domain\Query\LanguageQueryInterface: '@Ergonode\Core\Persistence\Dbal\Query\DbalLanguageQuery'
    Ergonode\Core\Application\Provider\DirectoryProviderInterface: '@Ergonode\Core\Application\Provider\SimpleDirectoryProvider'

    Ergonode\Core\Infrastructure\JMS\Serializer\Handler\FormErrorHandler:
        arguments:
            - '@translator'
            - '@Ergonode\Core\Infrastructure\Mapper\FormErrorMapper'

    Ergonode\Core\Infrastructure\JMS\Serializer\Handler\ExceptionHandler:
        arguments:
            - '%kernel.debug%'

    Ergonode\Core\Infrastructure\JMS\Serializer\HandlerRegistry:
        decorates: 'jms_serializer.handler_registry'
        arguments:
            $handlers: !tagged 'jms_serializer.subscribing_handler'
            $registry: '@Ergonode\Core\Infrastructure\JMS\Serializer\HandlerRegistry.inner'

    jms_serializer.form_error_handler: '@Ergonode\Core\Infrastructure\JMS\Serializer\Handler\FormErrorHandler'

    # overriding message serializer
    messenger.transport.serializer:
        class: 'Ergonode\Core\Infrastructure\Transport\Serializer\TransportMessageSerializer'
